# Site settings
title: nljs.nl
email: jpwesselink@gmail.com
description: > # JavaScript events in the Netherlands
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nljs.nl" # the base hostname & protocol for your site
twitter_username: jp10k
github_username:  jpwesselink
thankyou: sytac.io
# Build settings
markdown: kramdown
future: true
